name: Replay Cypress
author: Replay.io
description: Run and record Cypress tests with Replay
inputs:
  api-Key:
    required: true
    description: "Replay.io API Key"
  browser:
    description: "Replay Browser to use"
    default: Replay Firefox
  command:
    description: "Command to run tests"
    default: npx cypress run
  public:
    description: "Makes the uploaded replay viewable by everyone"
    default: false
  upload-all:
    description: "Upload all recordings instead of only recordings of failed tests"
    default: false
  working-directory:
    description: "Relative path to app"
    default: "."
  test-run-id:
    description: "UUID used to group tests into a run"
runs:
  using: composite
  steps:
    - name: Install Dependencies
      run: npm install --prefix $GITHUB_ACTION_PATH uuid
      shell: bash
    - name: Generate Test Run ID
      id: test-run-id
      uses: actions/github-script@v6
      with:
        result-encoding: string
        script: |
          const uuid = require(require('path').join(process.env.GITHUB_ACTION_PATH, 'node_modules', 'uuid'));
          let value = "${{ inputs.test-run-id }}";
          if (!uuid.validate(value)) {
            console.error("test-run-id was invalid. Generating a new value.");
            value = uuid.v4();
          }
          return value;
    - name: Generate metadata file
      id: metadata-file
      run: echo "TMP_FILE=$(mktemp)" >> $GITHUB_OUTPUT
      shell: bash
    - run: ${{ inputs.command }} --browser "${{ inputs.browser }}"
      shell: sh
      working-directory: ${{ inputs.working-directory }}
      env:
        RECORD_REPLAY_DISABLE_REDUX_DEVTOOLS: 1
        RECORD_REPLAY_TEST_RUN_ID: ${{ steps.test-run-id.outputs.result }}
        # RECORD_ALL_CONTENT: 1
        RECORD_REPLAY_METADATA_FILE: ${{ steps.metadata-file.outputs.TMP_FILE }}
        # TODO [ryanjduffy]: Include this later when we want to hide the command
        # log in recordings.
        # CYPRESS_NO_COMMAND_LOG: 1
    - name: "Upload Recordings"
      id: "upload-recordings"
      uses: replayio/action-upload@v0.4.7
      if: ${{ always() }}
      with:
        api-key: ${{ inputs.api-key }}
        public: ${{ inputs.public }}
        filter: ${{ inputs.upload-all == 'true' && 'function($v) { $v.metadata.test.result }' || 'function($v) { $v.metadata.test.result = "failed" }' }}
