name: Replay Cypress
author: Replay.io
description: Run and record Cypress tests with Replay
inputs:
  apiKey:
    required: true
    description: "Replay.io API Key"
  browser:
    description: "Replay Browser to use"
    default: Replay Firefox
  command:
    description: "Command to run tests"
    default: npx cypress run
  issue-number:
    description: "Pull Request on which to comment results"
  public:
    description: "Makes the uploaded replay viewable by everyone"
    default: false
  upload-all:
    description: "Upload all recordings instead of only recordings of failed tests"
    default: false
  working-directory:
    description: "Relative path to app"
    default: "."
runs:
  using: composite
  steps:
    - name: Generate Test Run ID
      id: test-run-id
      run: echo "::set-output name=UUID::$(uuidgen | tr A-Z a-z)"
      shell: bash
    - name: Generate metadata file
      id: metadata-file
      run: echo "::set-output name=TMP_FILE::$(mktemp)"
      shell: bash
    - run: npm i --legacy-peer-deps @replayio/cypress@">=0.2.0"
      shell: sh
    - run: ${{ inputs.command }} --browser "${{ inputs.browser }}"
      shell: sh
      working-directory: ${{ inputs.working-directory }}
      env:
        RECORD_REPLAY_TEST_RUN_ID: ${{ steps.test-run-id.outputs.UUID }}
        RECORD_ALL_CONTENT: 1
        RECORD_REPLAY_METADATA_FILE: ${{ steps.metadata-file.outputs.TMP_FILE }}
        # TODO [ryanjduffy]: Include this later when we want to hide the command
        # log in recordings.
        # CYPRESS_NO_COMMAND_LOG: 1
    - name: 'Upload Recordings'
      id: 'upload-recordings'
      uses: replayio/action-upload@v0.2.5
      if: ${{ always() }}
      with:
        apiKey: ${{ inputs.apiKey }}
        public: ${{ inputs.public }}
        filter: ${{ !inputs.upload-all && 'function($v) { $v.metadata.test.result = "failed" and $v.status = "onDisk" }' || 'function($v) { $v.metadata.test.result and $v.status = "onDisk" }' }}
      env:
        RECORD_REPLAY_API_KEY: ${{ inputs.apiKey }}
    - name: 'Comment PR'
      uses: replayio/action-comment@v0.1.0
      if: ${{ always() }}
      with:
        api-key: ${{ inputs.apiKey }}
        issue-number: ${{ github.event.pull_request.number }}
        recordings: ${{ steps.upload-recordings.outputs.recordings }}
        test-run-id: ${{ steps.test-run-id.outputs.UUID }}

